name: End-to-end tests

on:
  workflow_call:
    inputs:
      controller-image-repository:
        description: "Define the controller container image repository"
        type: string
        required: false
        default: ""
      controller-image-tag:
        description: "Define the controller container image tag"
        required: false
        type: string
        default: ""
      controller-container-image-artifact:
        description: "Load the image used in the deployment from local artifact"
        type: string
        required: false
        default: ""
      policy-server-repository:
        description: "Define the policy server container image tag"
        type: string
        required: false
        default: "ghcr.io/kubewarden/policy-server"
      policy-server-tag:
        description: "Define the policy server container image tag"
        type: string
        required: false
        default: "latest"
      policy-server-container-image-artifact:
        description: "Define the artifact containing the policy server container image"
        type: string
        required: false
        default: ""
      end-to-end-tests-version:
        description: "The end-to-end tests version tag to be run"
        type: string
        required: false
        default: "latest"

jobs:
  tests-kubewarden-installation:
    name: "Kubewarden basic end-to-end tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout end-to-end repository"
        uses: actions/checkout@v2
        with:
          repository: "${{ github.repository_owner }}/kubewarden-end-to-end-tests"
          path: "e2e-tests"
      - name: "Checkout latest tag"
        if: ${{ inputs.end-to-end-tests-version == 'latest' }}
        shell: bash
        run: |
          cd e2e-tests
          git checkout `git rev-list --tags --max-count=1`
      - name: "Checkout end-to-end tests version"
        if: ${{ inputs.end-to-end-tests-version != 'latest' }}
        shell: bash
        run: |
          cd e2e-tests
          git checkout ${{ inputs.end-to-end-tests-version }}
      - name: "Setup bats testing framework"
        uses: mig4/setup-bats@v1.2.0
        with:
          bats-version: 1.5.0
      - name: "Create Kubernetes cluster with Kubewarden installed"
        uses: jvanz/setup-kubewarden-cluster-action@upgradetests
        with:
          controller-image-repository: ${{ inputs.controller-image-repository }}
          controller-image-tag: ${{ inputs.controller-image-tag }}
          controller-container-image-artifact: ${{ inputs.controller-container-image-artifact }}
          policy-server-repository: ${{ inputs.policy-server-repository }}
          policy-server-tag: ${{ inputs.policy-server-tag }}
          policy-server-container-image-artifact: ${{ inputs.policy-server-container-image-artifact }}
      - name: "Run all end-to-end tests"
        run: |
          make --directory e2e-tests runall
        shell: bash
      - name: "Uninstall Kuberwarden"
        run: |
          # TODO - share release with the create-kubewarden-cluster action
          helm uninstall -n kubewarden kubewarden-controller
          helm uninstall -n kubewarden kubewarden-crds
